name: bench
on:
  schedule:
    - cron: 0 */6 * * *
  push:
    branches:
      - main
jobs:
  hello_bench:
    name: 'Hello, bench!'
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: homestead
      DB_USER: root
      DB_PASSWORD: root

    permissions:
      id-token: write
      contents: write
      packages: write
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      
      mongodb:
        image: mongo:4.4.6
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: test
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Install Oha
        uses: baptiste0928/cargo-install@v1
        with:
          crate: oha
          version: 1.1.0
      
      - name: Generate internal benchmarks
        run: deno task bench

      - name: Push changes
        uses: actions-js/push@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
      
      - name: Run Build
        run: deno task build
          
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fastro
          entrypoint: modules/web/main.tsx
