name: bench
on:
  schedule:
    - cron: 0 */3 * * *
  push:
     branches:    
      - main
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
      - name: Install Oha
        uses: baptiste0928/cargo-install@v1
        with:
          crate: oha
          version: 0.5.5
      - name: Create index.html
        run: echo '<h1>hi</h1>' > index.html
      - name: Generate internal benchmarks
        run: deno task bench
      - name: Push changes
        uses: actions-js/push@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
