name: build
on:
  push:
     branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run hydrate
        run: deno task hydrate

      - name: Run tests
        run: deno task test
         
      - name: Generate report
        run: deno coverage cov --lcov > cov.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@v1
        with:
          path-to-lcov: ./cov.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fastro
          entrypoint: app/main.ts
