name: build
'on':
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: vx.x.x
      - run: deno lint --unstable
      - run: deno test -A --unstable
      - run: deno test -A --unstable --coverage=cov/
      - run: deno coverage --lcov cov/ > cov.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
