name: build
'on':
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
      - name: Install Oha
        uses: baptiste0928/cargo-install@v1
        with:
          crate: oha
          version: 0.5.5
      - run: deno lint --unstable
      - name: Run tests
        run: deno test -A --unstable --coverage=cov
      - name: Generate report
        run: deno coverage cov --lcov > cov.lcov
      - name: Generate internal benchmarks
        run: deno task bench
      - name: Coveralls
        uses: coverallsapp/github-action@v1
        with:
          path-to-lcov: ./cov.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: actions-js/push@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
