name: build
on:
  push:
     branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno lint --unstable http
      - run: deno lint --unstable examples

      - name: Run tests
        run: deno task test
      
      - name: Run hydrate
        run: deno task hydrate
      
      - name: Generate report
        run: deno coverage cov --lcov > cov.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@v1
        with:
          path-to-lcov: ./cov.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Install Oha
      #   uses: baptiste0928/cargo-install@v1
      #   with:
      #     crate: oha
      #     version: 0.6.0

      # - name: Generate internal benchmarks
      #   run: deno task bench

      - name: Push changes
        uses: actions-js/push@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
      
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fastro
          entrypoint: app/main.ts

      
