name: build
on:
  push:
     branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Init import_map
        run: cp import_map.json.prod import_map.json

      - name: Run build
        run: deno task build

      - name: Run tests
        run: deno task test
         
      - name: Generate report
        run: deno task coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ./cov.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
