name: build
'on':
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
      - run: deno lint --unstable
      - name: Run tests
        run: deno task test
      - name: Generate report
        run: deno task coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v1
        with:
          path-to-lcov: ./cov_profile.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
