name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.4.5
      - run: deno --version
      - run: deno lint --unstable
      - run: deno fmt --check
      - run: deno test -A
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'fastrodev/fastro'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}