name: build
on:
  push:
     branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno lint --unstable http
      - run: deno lint --unstable examples

      - name: Run hydrate
        run: deno task hydrate
      
      - name: Run tests
        run: deno task test